from __future__ import annotations

import hashlib
import json
from pathlib import Path
import subprocess
import sys
import zipfile

import pytest


ROOT = Path(__file__).resolve().parents[2]
REQUIRED_GATES = {
    "public_surface",
    "removed_vocabulary",
    "markdown_links",
    "ruff",
    "python_unit_contracts",
    "python_integration",
    "sqlite_store",
    "postgres_store",
    "ui_vitest",
    "ui_build",
    "browser_desktop_mobile",
    "wheel_metadata",
    "wheel_smoke",
    "external_python",
    "external_fastapi",
    "external_langchain",
    "external_llamaindex",
    "artifact_digest",
}


@pytest.fixture
def release_evidence_path() -> Path:
    value = Path.cwd() / "artifacts" / "release-evidence.json"
    if not value.is_file():
        pytest.skip("release evidence is generated by the release-candidate proof")
    return value


def test_release_evidence_has_every_passing_gate(release_evidence_path: Path) -> None:
    evidence = json.loads(release_evidence_path.read_text(encoding="utf-8"))
    gates = {gate["id"]: gate for gate in evidence["gates"]}
    assert REQUIRED_GATES <= gates.keys()
    assert all(gates[name]["status"] == "passed" for name in REQUIRED_GATES)
    assert all(gates[name]["command"] for name in REQUIRED_GATES)
    assert all(gates[name]["artifacts"] for name in REQUIRED_GATES)
    assert evidence["distribution"]["sha256"]
    assert evidence["version"] == evidence["distribution"]["version"]
    assert {proof["id"] for proof in evidence["workflow_proofs"]} == {
        "retrieval_release_decision",
        "candidate_lineage_workflow",
    }


def test_generator_rejects_missing_or_mismatched_gate_results(tmp_path: Path) -> None:
    dist = tmp_path / "dist"
    results = tmp_path / "results"
    dist.mkdir()
    results.mkdir()
    wheel = dist / "retrieval_observatory-0.5.0-py3-none-any.whl"
    with zipfile.ZipFile(wheel, "w") as archive:
        archive.writestr("retrieval_observatory-0.5.0.dist-info/METADATA", "Metadata-Version: 2.1\nVersion: 0.5.0\n")
    digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
    for gate in REQUIRED_GATES - {"artifact_digest"}:
        (results / f"{gate}.json").write_text(
            json.dumps(
                {
                    "id": gate,
                    "status": "passed",
                    "command": f"check {gate}",
                    "artifacts": [f"{gate}.txt"],
                    "wheel_sha256": digest,
                    "timestamp": "2026-07-16T00:00:00Z",
                }
            ),
            encoding="utf-8",
        )
    completed = subprocess.run(
        [
            sys.executable,
            str(ROOT / "scripts" / "generate_release_evidence.py"),
            "--results-dir",
            str(results),
            "--dist",
            str(dist),
            "--output-json",
            str(tmp_path / "release-evidence.json"),
            "--output-markdown",
            str(tmp_path / "release-evidence.md"),
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert completed.returncode != 0
    assert "artifact_digest" in completed.stderr


def test_generator_writes_digest_bound_evidence(tmp_path: Path) -> None:
    dist = tmp_path / "dist"
    results = tmp_path / "results"
    dist.mkdir()
    results.mkdir()
    wheel = dist / "retrieval_observatory-0.5.0-py3-none-any.whl"
    with zipfile.ZipFile(wheel, "w") as archive:
        archive.writestr("retrieval_observatory-0.5.0.dist-info/METADATA", "Metadata-Version: 2.1\nVersion: 0.5.0\n")
    digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
    for gate in REQUIRED_GATES:
        (results / f"{gate}.json").write_text(
            json.dumps(
                {
                    "id": gate,
                    "status": "passed",
                    "command": f"check {gate}",
                    "artifacts": [f"{gate}.txt"],
                    "wheel_sha256": digest,
                    "timestamp": "2026-07-16T00:00:00Z",
                }
            ),
            encoding="utf-8",
        )
    output_json = tmp_path / "release-evidence.json"
    output_markdown = tmp_path / "release-evidence.md"
    subprocess.run(
        [
            sys.executable,
            str(ROOT / "scripts" / "generate_release_evidence.py"),
            "--results-dir",
            str(results),
            "--dist",
            str(dist),
            "--output-json",
            str(output_json),
            "--output-markdown",
            str(output_markdown),
        ],
        check=True,
    )
    evidence = json.loads(output_json.read_text(encoding="utf-8"))
    assert evidence["distribution"]["sha256"] == digest
    assert {gate["id"] for gate in evidence["gates"]} == REQUIRED_GATES
    assert {proof["gate"] for proof in evidence["workflow_proofs"]} == {"python_integration"}
    assert all(proof["tests"] for proof in evidence["workflow_proofs"])
    assert output_markdown.read_text(encoding="utf-8").startswith("# retobs release evidence\n")
