from __future__ import annotations

from collections import defaultdict
from statistics import mean, pstdev
from typing import Dict, Iterable, List, Set

from retrieval_observatory.metrics.ranking import dedupe_preserve_rank
from retrieval_observatory.types import CandidateLineage, PipelineResult


def compute_candidate_lineage(result: PipelineResult) -> List[CandidateLineage]:
    """Return per-stage candidate flow for a single pipeline result."""
    lineages: List[CandidateLineage] = []
    prev_ids: Set[str] = set()

    for snap in result.snapshots:
        curr_ids = {d.id for d in snap.documents}
        if not prev_ids:
            # First stage — everything is new
            lineages.append(CandidateLineage(
                stage_index=snap.stage_index,
                stage_id=snap.stage_id,
                entered=sorted(curr_ids),
                survived=[],
                dropped=[],
                churn_rate=0.0,
            ))
        else:
            survived = sorted(curr_ids & prev_ids)
            dropped = sorted(prev_ids - curr_ids)
            entered = sorted(curr_ids - prev_ids)
            churn_rate = len(dropped) / max(len(prev_ids), 1)
            lineages.append(CandidateLineage(
                stage_index=snap.stage_index,
                stage_id=snap.stage_id,
                entered=entered,
                survived=survived,
                dropped=dropped,
                churn_rate=churn_rate,
            ))
        prev_ids = curr_ids

    return lineages


def compute_churn_rate(lineages: List[CandidateLineage]) -> float:
    """Average churn rate across all non-first stages (0.0 if single-stage pipeline)."""
    non_first = [lin.churn_rate for lin in lineages if lin.stage_index > 0]
    return mean(non_first) if non_first else 0.0


def build_query_diagnostics(
    run_id: str,
    results: List[PipelineResult],
    qrels: Dict,
) -> List[Dict]:
    """Create per-query, per-pipeline diagnostic labels from stored stage outputs."""
    by_query: Dict[str, List[PipelineResult]] = defaultdict(list)
    for result in results:
        by_query[result.query_id].append(result)

    recall_by_query: Dict[str, List[float]] = defaultdict(list)
    final_sets: Dict[tuple, Set[str]] = {}
    first_sets: Dict[tuple, Set[str]] = {}

    for result in results:
        relevant = _relevant_set(qrels.get(result.query_id))
        if not relevant or result.status != "OK" or not result.snapshots:
            recall_by_query[result.query_id].append(0.0)
            continue
        first = set(d.id for d in result.snapshots[0].documents)
        final = set(d.id for d in result.snapshots[-1].documents)
        first_sets[(result.query_id, result.pipeline_id)] = first
        final_sets[(result.query_id, result.pipeline_id)] = final
        recall_by_query[result.query_id].append(len(final & relevant) / len(relevant))

    buckets = {
        query_id: _difficulty_bucket(scores)
        for query_id, scores in recall_by_query.items()
    }

    rows: List[Dict] = []
    for result in results:
        relevant = _relevant_set(qrels.get(result.query_id))
        stage_hits = {}
        labels = []
        if result.status != "OK":
            labels.append("unstable")

        for snap in result.snapshots:
            ids = set(dedupe_preserve_rank([d.id for d in snap.documents]))
            stage_hits[str(snap.stage_index)] = sorted(ids & relevant)

        final_ids = final_sets.get((result.query_id, result.pipeline_id), set())
        first_ids = first_sets.get((result.query_id, result.pipeline_id), set())
        missing = sorted(relevant - final_ids)

        # Union of every stage's candidates. For hybrid / fan-in pipelines a relevant doc
        # may be generated by a later (fused) stage rather than stage 0, so candidate_miss
        # must mean "no stage ever surfaced it" — otherwise a *successful* query whose doc
        # came from the dense arm would be inverted into a retrieval-failure label.
        any_stage_ids: Set[str] = set()
        for snap in result.snapshots:
            any_stage_ids |= {d.id for d in snap.documents}

        if relevant and not any_stage_ids & relevant:
            labels.append("candidate_miss")
        elif relevant and not first_ids & relevant and final_ids & relevant:
            # Surfaced only by a later / parallel stage and carried through to the final
            # results — an accurate, non-failure signal (not the inverted candidate_miss).
            labels.append("late_stage_recovery")

        if len(result.snapshots) > 1 and first_ids & relevant and not final_ids & relevant:
            labels.append("reranker_drop")

        # Late-stage drop: relevant doc survived to penultimate stage but absent from final
        if len(result.snapshots) > 2:
            penultimate_ids = {d.id for d in result.snapshots[-2].documents}
            if penultimate_ids & relevant and not final_ids & relevant:
                if "reranker_drop" not in labels:
                    labels.append("late_stage_drop")

        # Ranking failure: relevant doc present in final candidates but ranked below K
        if relevant and final_ids & relevant:
            max_k = len(result.snapshots[-1].documents)
            top_k_ids = {d.id for d in result.snapshots[-1].documents if d.rank <= max_k}
            if not top_k_ids & relevant:
                labels.append("ranking_failure")

        any_stage_hit = any(row_hits for row_hits in stage_hits.values())
        if relevant and not any_stage_hit and not any(
            final_sets.get((result.query_id, pid), set()) & relevant
            for pid in _pipeline_ids(by_query[result.query_id])
        ):
            labels.append("id_or_qrel_issue")

        # Cross-pipeline lexical/semantic hints via adapter name as lightweight signal
        if result.pipeline_id.lower().find("bm25") >= 0 and not final_ids & relevant:
            if any(
                "dense" in pid.lower() and final_sets.get((result.query_id, pid), set()) & relevant
                for pid in _pipeline_ids(by_query[result.query_id])
            ):
                labels.append("lexical_mismatch")
        if "dense" in result.pipeline_id.lower() and not final_ids & relevant:
            if any(
                "bm25" in pid.lower() and final_sets.get((result.query_id, pid), set()) & relevant
                for pid in _pipeline_ids(by_query[result.query_id])
            ):
                labels.append("semantic_mismatch")

        bucket = buckets.get(result.query_id, "unknown")
        if bucket == "unstable" and "unstable" not in labels:
            labels.append("unstable")

        # Compute candidate lineage for churn metrics
        lineages = compute_candidate_lineage(result) if result.status == "OK" else []
        churn = compute_churn_rate(lineages)

        rows.append(
            {
                "run_id": run_id,
                "query_id": result.query_id,
                "pipeline_id": result.pipeline_id,
                "difficulty_bucket": bucket,
                "failure_labels": sorted(set(labels)),
                "missing_relevant_ids": missing,
                "stage_hits": stage_hits,
                "churn_rate": round(churn, 4),
            }
        )
    return rows


def aggregate_diagnostics(rows: List[Dict]) -> Dict:
    by_bucket: Dict[str, int] = defaultdict(int)
    by_label: Dict[str, int] = defaultdict(int)
    by_pipeline: Dict[str, Dict] = {}

    for row in rows:
        by_bucket[row["difficulty_bucket"]] += 1
        pid = row.get("pipeline_id", "unknown")
        if pid not in by_pipeline:
            by_pipeline[pid] = {"n": 0, "labels": defaultdict(int), "difficulty_buckets": defaultdict(int)}
        by_pipeline[pid]["n"] += 1
        by_pipeline[pid]["difficulty_buckets"][row["difficulty_bucket"]] += 1
        for label in row.get("failure_labels", []):
            by_label[label] += 1
            by_pipeline[pid]["labels"][label] += 1

    return {
        "difficulty_buckets": dict(by_bucket),
        "failure_labels": dict(by_label),
        "by_pipeline": {
            pid: {
                "n": data["n"],
                "labels": dict(data["labels"]),
                "difficulty_buckets": dict(data["difficulty_buckets"]),
            }
            for pid, data in by_pipeline.items()
        },
        "n": len(rows),
    }


def _relevant_set(raw: object) -> Set[str]:
    if isinstance(raw, dict):
        return {doc_id for doc_id, grade in raw.items() if int(grade) > 0}
    return set(raw or [])


def _difficulty_bucket(scores: List[float]) -> str:
    if not scores:
        return "unknown"
    avg = mean(scores)
    spread = pstdev(scores) if len(scores) > 1 else 0.0
    if spread >= 0.25:
        return "discriminative"
    if avg >= 0.8:
        return "easy"
    if avg <= 0.2:
        return "hard"
    return "medium"


def _pipeline_ids(results: Iterable[PipelineResult]) -> List[str]:
    return [result.pipeline_id for result in results]


def predict_retrieval_risks(query_text: str) -> List[str]:
    """Pre-execution risk signals from query text features (no classifier required).

    Returns actionable hints — not measured failure predictions.
    """
    from retrieval_observatory.classifier.features import extract_features
    from retrieval_observatory.tracing.enrich import predict_difficulty

    risks: List[str] = []
    f = extract_features(query_text)
    difficulty = predict_difficulty(query_text)

    if difficulty in ("hard", "extreme"):
        risks.append("high_difficulty_query")
    if f.get("has_temporal_anchor", 0) >= 1.0:
        risks.append("temporal_sensitivity")
    if f.get("has_comparison", 0) >= 1.0:
        risks.append("comparison_query")
    if f.get("token_count", 0) > 20:
        risks.append("long_query_may_need_higher_k")
    if f.get("has_negation", 0) >= 1.0:
        risks.append("negation_may_hurt_lexical_match")

    return risks
