from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional


@dataclass
class CorpusScenario:
    """A structural pattern in a corpus that commonly causes retrieval failures."""
    scenario_id: str
    scenario_type: Literal["temporal", "alias"]
    anchor_doc_ids: List[str]   # documents that form the scenario
    evidence_summary: str       # human-readable description of why this is a scenario
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SyntheticQuery:
    """A generated query targeting a specific corpus failure scenario."""
    query_id: str
    text: str
    scenario_id: str
    query_type: Literal["paraphrase", "temporal", "adversarial"]
    positive_doc_ids: List[str]             # extractive ground truth (grade 2)
    difficulty_label: Literal["easy", "medium", "hard", "extreme"] = "medium"
    failure_category: Optional[str] = None
    validated: bool = False                 # whether LLM validation pass was run
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SyntheticDataset:
    """A corpus-specific stress-test evaluation dataset generated by Forge."""
    dataset_id: str
    corpus: Dict[str, Dict]                          # doc_id -> {"text": ..., "title": ...}
    queries: List[SyntheticQuery]
    qrels: Dict[str, Dict[str, int]]                 # query_id -> {doc_id -> grade}
    scenarios: List[CorpusScenario]
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def summary(self) -> Dict[str, Any]:
        scenario_counts: Dict[str, int] = {}
        for s in self.scenarios:
            scenario_counts[s.scenario_type] = scenario_counts.get(s.scenario_type, 0) + 1

        type_counts: Dict[str, int] = {}
        diff_counts: Dict[str, int] = {}
        for q in self.queries:
            type_counts[q.query_type] = type_counts.get(q.query_type, 0) + 1
            diff_counts[q.difficulty_label] = diff_counts.get(q.difficulty_label, 0) + 1

        return {
            "dataset_id": self.dataset_id,
            "corpus_size": len(self.corpus),
            "n_scenarios": len(self.scenarios),
            "scenarios_by_type": scenario_counts,
            "n_queries": len(self.queries),
            "queries_by_type": type_counts,
            "queries_by_difficulty": diff_counts,
            "validated": sum(1 for q in self.queries if q.validated),
            "created_at": self.created_at.isoformat(),
        }
